#
# Settings
#
backend:
  name: git-gateway
  branch: master
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
media_folder: "site/static/media/uploads"
public_folder: "/media"
display_url: https://zealous-pike-2f4b9b.netlify.com
logo_url: https://zealous-pike-2f4b9b.netlify.com/media/logo-image-text.png
# Beta features
publish_mode: editorial_workflow
#
# Collections
#
collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - label: "Type"
            name: "type"
            widget: "hidden"
            default: "about"
          - label: "Page"
            name: "page"
            widget: hidden
            default: "/about.html"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Hero Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Media Overlay/Background Color"
                name: "overlay"
                widget: "select"
                options: ["none","blue","green","red","gray - dark","gray - light"]
              - label: "Hero Title"
                name: "title"
                widget: "string"
              - label: "Hero Subtitle"
                name: "subtitle"
                widget: "string"
                required: false
              - label: "Hero Text"
                name: "text"
                widget: "string"
                required: false
              - label: "Alignment"
                name: "alignment"
                widget: "select"
                options: ["left","center","right"]
          - label: "Who Is Friends of SHP?"
            name: "who"
            widget: "object"
            fields:
              - label: "title"
                name: title
                widget: string
              - label: "text"
                name: text
                widget: markdown
                required: false
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Direction"
                name: "direction"
                widget: "select"
                options: ["ltr","rtl"]
                required: false
              - label: "background color"
                name: "overlay"
                widget: select
                options: ["red", "blue", "green", "none"]
          - label: "What Are Our Goals?"
            name: "what"
            widget: "object"
            fields:
              - label: "title"
                name: title
                widget: string
              - label: "text"
                name: text
                widget: markdown
                required: false
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Direction"
                name: "direction"
                widget: "select"
                options: ["ltr","rtl"]
                required: false
              - label: "background color"
                name: "overlay"
                widget: select
                options: ["red", "blue", "green", "none"]
          - label: "History of SHP?"
            name: "history"
            widget: "object"
            fields:
              - label: "title"
                name: title
                widget: string
              - label: "text"
                name: text
                widget: markdown
                required: false
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Direction"
                name: "direction"
                widget: "select"
                options: ["ltr","rtl"]
                required: false
              - label: "background color"
                name: "overlay"
                widget: "select"
                options: ["red", "blue", "green", "none"]
          - label: "Plans for SHP"
            name: "plans"
            widget: "object"
            fields:
              - label: "title"
                name: "title"
                widget: "string"
              - label: "text"
                name: "text"
                widget: markdown
                required: false
              - label: "list"
                name: "list"
                widget: "list"
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Direction"
                name: "direction"
                widget: "select"
                options: ["ltr","rtl"]
                required: false
              - label: "background color"
                name: "overlay"
                widget: select
                options: ["red", "blue", "green", "none"]
          - label: "The Beneficiaries"
            name: "beneficiaries"
            widget: "object"
            fields:
              - label: "title"
                name: "title"
                widget: "string"
              - label: "text"
                name: "text"
                widget: markdown
                required: false
              - label: "list"
                name: "list"
                widget: "list"
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Direction"
                name: "direction"
                widget: "select"
                options: ["ltr","rtl"]
                required: false
              - label: "background color"
                name: "overlay"
                widget: select
                options: ["red", "blue", "green", "none"]
          - label: "Call To Action"
            name: "cta"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button Text"
                name: "button_text"
                widget: "string"
              - label: "Button Destination"
                name: "button_destination"
                widget: "string"
              - label: "Button Color"
                name: "button_color"
                widget: "select"
                options: ["red", "blue", "green", "none"]
              - label: "Background Color"
                name: "background_color"
                widget: "select"
                options: ["red", "blue", "green", "none"]
              - label: "Alignment"
                name: alignment
                widget: "select"
                options: ["center", "left", "right"]
                required: false
          - label: "People of Friends of SHP"
            name: "people"
            widget: "object"
            fields: 
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
                required: false
              - label: "People"
                name: "people"
                widget: "list"
                fields: 
                  - label: "Person"
                    name: "person"
                    widget: "object"
                    fields: 
                      - {label: Name, name: name, widget: string}
                      - {label: Byline, name: byline, widget: string, required: false}
                      - {label: Bio, name: bio, widget: markdown}
                      - {label: Image, name: image, widget: image}
          - label: "Donors to Friends of SHP"
            name: "donors"
            widget: "object"
            fields: 
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
                required: false
              - label: "donors"
                name: "donors"
                widget: "list"
                fields: 
                  - label: "Donor"
                    name: "donor"
                    widget: "object"
                    fields: 
                      - {label: Name, name: name, widget: string}
                      - {label: Byline, name: byline, widget: string}
                      - {label: Bio, name: bio, widget: markdown}
                      - {label: Image, name: image, widget: image}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
            - label: "SEO noindex"
              name: "noindex"
              widget: boolean
              required: false
            - label: "SEO nofollow"
              name: "nofollow"
              widget: boolean
              required: false
            - label: "SEO Description"
              name: "seo_description"
              widget: "text"
              required: false
            - label: "Meta Title"
              name: "metatitle"
              widget: "text"
              required: false
      - label: "Contact"
        name: "contact"
        file: "site/content/contact.md"
        fields:
          - label: "Type"
            name: "type"
            widget: "hidden"
            default: "contact"
          - label: "Page"
            name: "page"
            widget: "hidden"
            default: "/contact.html"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Hero Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Media Overlay/Background Color"
                name: "overlay"
                widget: "select"
                options: ["none","blue","green","red","gray - dark","gray - light"]
              - label: "Hero Title"
                name: "title"
                widget: "string"
              - label: "Hero Subtitle"
                name: "subtitle"
                widget: "string"
                required: false
              - label: "Hero Text"
                name: "text"
                widget: "string"
                required: false
              - label: "Alignment"
                name: "alignment"
                widget: "select"
                options: ["left","center","right"]      
          - label: "Text"
            name: "text"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: false
              - label: "Text"
                name: "text"
                widget: "markdown"
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
            - label: "SEO noindex"
              name: "noindex"
              widget: boolean
              required: false
            - label: "SEO nofollow"
              name: "nofollow"
              widget: boolean
              required: false
            - label: "SEO Description"
              name: "seo_description"
              widget: "text"
              required: false
            - label: "Meta Title"
              name: "metatitle"
              widget: "text"
              required: false
      - label: "How to Help"
        name: "how_to_help"
        file: "site/content/how-to-help.md"
        fields:
          - label: "Type"
            name: "type"
            widget: "hidden"
            default: "how-to-help"
          - label: "Page"
            name: "page"
            widget: "hidden"
            default: "/how-to-help.html"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Hero Image"
                name: "image"
                widget: "image"
                required: false
                hint: "Preferred photo dimensions are ### X ###." #@todo
              - label: "Media Overlay/Background Color"
                name: "overlay"
                widget: "select"
                options: ["none","blue","green","red","gray - dark","gray - light"]
              - label: "Hero Title"
                name: "title"
                widget: "string"
              - label: "Hero Subtitle"
                name: "subtitle"
                widget: "string"
                required: false
              - label: "Hero Text"
                name: "text"
                widget: "string"
                required: false
              - label: "Alignment"
                name: "alignment"
                widget: "select"
                options: ["left","center","right"]
          - label: "Giving"
            name: "giving"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: markdown
              - label: "Level"
                name: "level"
                widget: "list"
                fields:
                  - {label: Name, name: name, widget: "String"}
                  - {label: Amount, name: amount, widget: number, valueType: int}
          - label: "Call To Action"
            name: "cta"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button Text"
                name: "button_text"
                widget: "string"
              - label: "Button Destination"
                name: "button_destination"
                widget: "string"
              - label: "Button Color"
                name: "button_color"
                widget: "select"
                options: ["red", "blue", "green", "none"]
              - label: "Background Color"
                name: "background_color"
                widget: "select"
                options: ["red", "blue", "green", "none"]
              - label: "Alignment"
                name: alignment
                widget: "select"
                options: ["center", "left", "right"]
                required: false
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
            - label: "SEO noindex"
              name: "noindex"
              widget: boolean
              required: false
            - label: "SEO nofollow"
              name: "nofollow"
              widget: boolean
              required: false
            - label: "SEO Description"
              name: "seo_description"
              widget: "text"
              required: false
            - label: "Meta Title"
              name: "metatitle"
              widget: "text"
              required: false

          
