#
# Settings
#
backend:
  name: git-gateway
  branch: master
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
media_folder: "site/static/media/uploads"
public_folder: "/media"
display_url: https://zealous-pike-2f4b9b.netlify.com
logo_url: https://zealous-pike-2f4b9b.netlify.com/media/logo-image-text.png
# Beta features
publish_mode: editorial_workflow
#
# Collections
#
collections:
  # Pages
  - name: "Pages"
    label: "Page"
    folder: "site/content/pages"
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Menu Weight"
        name: "weight"
        widget: "number"
        default: "0"
        valueType: "int"
        min: 0
        max: 99
        hint: "The higher the number, the lower/further right it will appear in the menu. A 0 leaves a page out of the main navigation."
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - label: "Hero Image"
            name: "image"
            widget: "image"
            required: false
            hint: "Preferred photo dimensions are ### X ###." #@todo
          - label: "Media Overlay/Background Color"
            name: "overlay"
            widget: "select"
            options: ["none","blue","green","red","gray - dark","gray - light"]
          - label: "Hero Title"
            name: "title"
            widget: "string"
            pattern: /^[a-z]{0,75}$/
          - label: "Hero Text"
            name: "text"
            widget: "string"
            pattern: /^[a-z]{0,250}$/
            required: false
          - label: "Alignment"
            name: "alignment"
            widget: "select"
            options: ["left","center","right"]
      - label: "Text Section"
        name: "text"
        widget: "object"
        fields: 
          - label: "title"
            name: title
            widget: string
            required: false
          - label: "text"
            name: text
            widget: markdown
          - label: "button"
            name: button
            widget: string
            required: false
          - label: "background color"
            name: background-color
            widget: select
            options: ["red", "blue", "green", "none"]
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "SEO Description"
        name: "seo_description"
        widget: "text"
        required: false
      - label: "Meta Title"
        name: "metatitle"
        widget: "text"
        required: false


